name: privacypanda-dev
channels:
  - conda-forge
dependencies:
  - python>=3.7.*
  - numpy >=1.16  # for numeric arrays
  - pandas >= 1.0.0
# notebooks
  - jupyter  # for notebooks
  - jupyterlab  # for notebooks IDE
  - nodejs  # for jupyterlab build
  - watermark  # for traceability in notebooks
# unit testing
  - pytest >=4.4  # for unit testing
# code quality
  - black  # for automatic code formatting
  - isort  # for import standardization
  - flake8  # for linting
# utilities
  - pip >=19  # for native python installer
  - pip:
    - -e .  # project code
